version: '2'

services:
        nginx:
                image: nginx
                restart: always
                ports:
                        - 443:443
                        - 80:80
                volumes:
                        - ./nginx/conf.d:/etc/nginx/conf.d
                        - ./nginx/keys:/etc/nginx/keys
                        - ./nginx/.htpasswd:/etc/nginx/.htpasswd
                        - ./www:/srv/
